### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by ssenkooto1** [jbrime15/Review#2]
**To highlight** 
- All linters passed and there were no problems 
- Good commit history.
- Your design looks fantastic.
- Good PR description: could use a few more details to support evidence of the requirements of the project.
- Your design looks great.

- Semantic tags were not implemented properly.

Review for Jubril

**Comment by jbrime15** [comment]
The Semantics was for the trials before joining Microverse.

**Comment by ssenkooto1** [comment]
> The Semantics was for the trials before joining Microverse.

**Comment by ssenkooto1** [comment]
Ok: I thought it was the first project. sorry about that
